### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by samuelsolis** [Drupalcat/summer2017#3]
Hi, in the site, the spanish and english versions of the sponsor 2017 pdf seems broke.

The link is inside "Con la entrada Love package estarás ayudando a hacer realidad este evento y te lo agradeceremos", the url linked are:

http://summer2017.drupal.cat/es/assets/files/drupal-summer-barcelona-2017-sponsor-es.pdf#page-6
and
http://summer2017.drupal.cat/en/assets/files/drupal-summer-barcelona-2017-sponsor-en.pdf#page=6

**Comment by espurnes** [comment]
I see, I will fix it in some minutes. Thank you.

**Comment by espurnes** [comment]
Fix it

**Comment by samuelsolis** [comment]
It seem resolved, Thanks @espurnes
